version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev-deps:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "pre-commit"
          - "build"
          - "twine"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
